version: 2

models:
  - name: mart_london_affordability_monthly
    columns:
      - name: date_month
        data_tests: [not_null]
      - name: area_code
        data_tests: [not_null]
      - name: area_name
        data_tests: [not_null]
      - name: price_to_earnings_ratio
        data_tests: [not_null]
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [date_month, area_code]

  - name: mart_london_property_type_latest
    columns:
      - name: date_month
        data_tests: [not_null]
      - name: area_code
        data_tests: [not_null]
      - name: average_price
        data_tests: [not_null]
      - name: property_type
        data_tests:
          - not_null
          - accepted_values:
              values: ["Detached", "Semi-detached", "Terraced", "Flat/Maisonette"]
      - name: price_to_earnings_ratio
        data_tests: [not_null]
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [area_code, property_type]

  - name: mart_london_borough_snapshot_latest
    columns:
      - name: date_month
        data_tests: [not_null]
      - name: area_code
        data_tests: [not_null]
      - name: area_name
        data_tests: [not_null]
      - name: price_to_earnings_ratio
        data_tests: [not_null]
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [area_code]
